# file: postgresql_install/tasks/main.yml
---
- name: Yum installing postgresql-libs, python-psycopg2
  yum:
    name:
      - 'postgresql-libs'
      - 'python-psycopg2'
    state: installed

- name: Yum installing PostgreSQL repo rpm
  yum:
    name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
    state: installed

- name: Yum installing client and server packages
  yum:
    name:
      - 'postgresql{{ version }}'
      - 'postgresql{{ version }}-server'
    state: installed
  notify:
    - restart_postgresql

- name: Initializing via initdb
  shell: '/usr/pgsql-{{ point_release }}/bin/postgresql{{ version }}-setup initdb'
  args:
    creates: '/var/lib/pgsql/{{ point_release }}/data/base'
  notify:
    - restart_postgresql

- name: Opening firewall port 5432
  firewalld:
    port: 5432/tcp
    state: enabled
    permanent: yes
  notify:
    - restart_firewalld

- name: Starting PostgreSQL and restarting firewalld
  meta: flush_handlers

- name: Creating PostgreSQL role for {{ postgres_user }}
  postgresql_user:
    name: '{{ postgres_user }}'
    password: '{{ postgres_user_password }}'
    role_attr_flags: CREATEDB,NOSUPERUSER
  become: yes
  become_user: postgres
...
